// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_7EU5KJKbIVSK2bJfbIl6gPV-SOce_t8',
    appId: '1:266907081661:web:6134f7747f3f2d57c0d0d4',
    messagingSenderId: '266907081661',
    projectId: 'car-registration-c42cf',
    authDomain: 'car-registration-c42cf.firebaseapp.com',
    storageBucket: 'car-registration-c42cf.appspot.com',
    measurementId: 'G-XGJEBTSS2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-XmDkLGiO8PG_cQZ9yEl6QSyotMUdXJ4',
    appId: '1:266907081661:android:d7fd5f94dfa1c564c0d0d4',
    messagingSenderId: '266907081661',
    projectId: 'car-registration-c42cf',
    storageBucket: 'car-registration-c42cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi3pa4bWlOThVdYU1xJSkXzW_xaNlbNmQ',
    appId: '1:266907081661:ios:d08d0cbcfbc3f53cc0d0d4',
    messagingSenderId: '266907081661',
    projectId: 'car-registration-c42cf',
    storageBucket: 'car-registration-c42cf.appspot.com',
    iosBundleId: 'com.example.carRegistrations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi3pa4bWlOThVdYU1xJSkXzW_xaNlbNmQ',
    appId: '1:266907081661:ios:f7ef1628d45b5c67c0d0d4',
    messagingSenderId: '266907081661',
    projectId: 'car-registration-c42cf',
    storageBucket: 'car-registration-c42cf.appspot.com',
    iosBundleId: 'com.example.carRegistration.RunnerTests',
  );
}
